#!/usr/bin/env node
/* Regenerates js/snapshot.js, the offline fallback the page ships with.
   Runs the very same parser the browser uses, over the markdown route (which
   needs no DOM, so plain Node can execute it).

     node tools/snapshot.js
*/
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = 'https://umbraco.com/about-us/the-history-of-umbraco/';
const RELAY = 'https://r.jina.ai/' + SRC;

const window = { UD: {} };
new Function('window', 'DOMParser', fs.readFileSync(path.join(ROOT, 'js/parser.js'), 'utf8'))(window, undefined);
const parser = window.UD.parser;

(async () => {
  const res = await fetch(RELAY, { headers: { accept: 'text/plain' } });
  if (!res.ok) throw new Error('relay returned HTTP ' + res.status);
  const data = parser.parse(await res.text(), 'markdown');

  if (!data.years.length) throw new Error('no year blocks parsed - has the page changed shape?');

  data.via = 'snapshot';
  data.source = SRC;
  data.fetchedAt = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');

  const out =
    '/* Fallback data, generated by js/parser.js from the live history page on ' +
    data.fetchedAt.slice(0, 10) + '.\n' +
    '   The app always tries a live read first; this only keeps the page useful\n' +
    '   when the network or every CORS relay is unavailable.\n' +
    '   Regenerate with: node tools/snapshot.js  */\n' +
    'var UD = window.UD || (window.UD = {});\n' +
    'UD.snapshot = ' + JSON.stringify(data, null, 1) + ';\n';

  fs.writeFileSync(path.join(ROOT, 'js/snapshot.js'), out);
  console.log('wrote js/snapshot.js - ' + data.years.length + ' year entries, ' +
              data.years[0].label + ' to ' + data.years[data.years.length - 1].label);
})().catch(err => { console.error('snapshot failed:', err.message); process.exit(1); });
